# Generated by Django 3.0.6 on 2020-05-15 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО автора')),
                ('image', models.ImageField(blank=True, null=True, upload_to='author/', verbose_name='Фото автора')),
                ('text', models.TextField(verbose_name='Описание автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='CategoryBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, verbose_name='url')),
                ('published', models.BooleanField(default=True, verbose_name='Отображать?')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='book.CategoryBook', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='url')),
                ('text', models.TextField(verbose_name='Описание')),
                ('pages', models.PositiveIntegerField(default=0, verbose_name='Количество страниц')),
                ('years', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('file', models.FileField(upload_to='books/', verbose_name='Книга')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='url на внешний ресурс')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата редактирования')),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='books_img/', verbose_name='Главная фотография')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать?')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотрено')),
                ('author', models.ManyToManyField(to='book.AuthorBook', verbose_name='Автор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.CategoryBook', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Книги, журналы, сборники',
                'verbose_name_plural': 'Книги, журналы, сборники',
            },
        ),
    ]
