# Generated by Django 3.0.6 on 2020-05-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200517_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='url')),
                ('published', models.BooleanField(default=True, verbose_name='отображать?')),
            ],
            options={
                'verbose_name': 'Теги книг',
                'verbose_name_plural': 'Теги книг',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='book.TagBook'),
        ),
    ]
