# Generated by Django 3.0.6 on 2020-05-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200517_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='book.AuthorBook', verbose_name='Автор(ы)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='url (книги, сборника, журнала)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='book.TagBook'),
        ),
    ]
