# Generated by Django 3.0.6 on 2020-05-19 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20200519_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorbook',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='book.CategoryAuthor', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
