# Generated by Django 3.0.6 on 2020-05-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_authorbook_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Heir',
        ),
    ]
