# Generated by Django 3.0.6 on 2020-05-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_delete_heir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='tags',
        ),
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='book.TagBook', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='books_img/', verbose_name='Главная фотография'),
        ),
    ]
