# Generated by Django 3.0.6 on 2020-05-20 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20200520_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='tag',
        ),
    ]
