# Generated by Django 3.0.6 on 2020-05-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_remove_book_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='book.TagBook', verbose_name='Теги'),
        ),
    ]
